## Numpy:
Numpy is a fundamental library in computing in python. It provides support for arrays and matrices along with mathmatical functions to operate on these data struture.

In [1]:
import numpy as np

#### Creating arrays:
####     1 D arrays 

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
np.shape(arr)

(5,)

In [10]:
arr = arr.reshape(1,5)   #1 row and 5 columns

In [11]:
np.shape(arr)

(1, 5)

#### 2D array:

In [14]:
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


#### Some Important Numpy functions:

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])