## Numpy:
Numpy is a fundamental library in computing in python. It provides support for arrays and matrices along with mathmatical functions to operate on these data struture.

In [1]:
import numpy as np

#### Creating arrays:
####     1 D arrays 

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
np.shape(arr)

(5,)

In [5]:
arr = arr.reshape(1,5)   #1 row and 5 columns

In [6]:
np.shape(arr)

(1, 5)

#### 2D array:

In [7]:
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


#### Some Important Numpy functions:

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Identity matrix: 
    Diagonal elements are 1:

In [13]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

#### Attributes of Numpy:

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
print(f'Array: {arr}')
print(f'Shape: {np.shape(arr)}')
print(f'No of dimension: {np.ndim(arr)}')
print(f'No of elements: {np.size(arr)}')
print(f'Data type: {arr.dtype}')
print(f'Item Size(In bytes): {arr.itemsize}')

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
No of dimension: 2
No of elements: 6
Data type: int32
Item Size(In bytes): 4


#### Numpy Vectorization Operations:

In [15]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#### Elementwise addition Substraction Multiplication Division:

In [16]:
print(f'1) Addition: {arr1 + arr2}')
print(f'2) Substraction: {arr1 - arr2}')
print(f'3) Multiplication: {arr1 * arr2}')
print(f'4) Division: {arr1/arr2}')

1) Addition: [11 22 33 44 55]
2) Substraction: [ -9 -18 -27 -36 -45]
3) Multiplication: [ 10  40  90 160 250]
4) Division: [0.1 0.1 0.1 0.1 0.1]


##### *for above code, return type is ndarray. mind it.*

#### Universal function that applies on whole array:

In [17]:
arr1 = np.array([2,3,4,5,6])

#### 1) Square root:

In [18]:
print(f'Square root: {np.sqrt(arr1)}')

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]


#### 2) Exponential:  

In [19]:
print(f'Exponential: {np.exp(arr1)}')

Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


#### 3) Sin function:

In [20]:
print(f'Sin of array: {np.sin(arr1)}')

Sin of array: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


#### 4) natural log: 

In [21]:
print(f'Natural Log: {np.log(arr1)}')

Natural Log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


#### Array Slicing and Indexing: 

In [22]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f'Array: {arr}')

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [24]:
print(f'First row and first column: {arr[0][0]}')
print(f'Third row and second column: {arr[2][1]}')

First row and first column: 1
Third row and second column: 10


In [25]:
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [27]:
print(arr[0:2,1:3])

[[2 3]
 [6 7]]


In [28]:
print(arr[1:3,1:3])

[[ 6  7]
 [10 11]]


In [29]:
corner_matrix = arr[[0, -1]][:, [0, -1]]
print(corner_matrix)


[[ 1  4]
 [ 9 12]]


In [30]:
arr[0,-1]

4

In [31]:
arr[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr[0,-1]

4

In [36]:
arr[:,[0,-1]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

The first column (0) contains [1, 4, 7].

The last column (-1) contains [3, 6, 9].

So, the result extracts only these two columns from all rows.

In [40]:
arr[[0,-1]][:,[0,-1]]

array([[ 1,  4],
       [ 9, 12]])

arr[[0, -1]]:-  
This selects specific rows (0 and -1, i.e., the first and last rows).

The result is a new sub-array containing only those rows.

[:, [0, -1]]  
Now, we apply [:, [0, -1]] on the new sub-array:

: → Selects all rows from the sub-array.

[0, -1] → Selects first and last columns.
                            

In [41]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [44]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [48]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [51]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### Modify array elements:

In [54]:
arr[0][0] = 100

In [55]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [57]:
arr[1][2] = 200

In [58]:
arr

array([[100,   2,   3,   4],
       [  5,   6, 200,   8],
       [  9,  10,  11,  12]])