## Numpy:
Numpy is a fundamental library in computing in python. It provides support for arrays and matrices along with mathmatical functions to operate on these data struture.

In [1]:
import numpy as np

#### Creating arrays:
####     1 D arrays 

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
np.shape(arr)

(5,)

In [5]:
arr = arr.reshape(1,5)   #1 row and 5 columns

In [6]:
np.shape(arr)

(1, 5)

#### 2D array:

In [7]:
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


#### Some Important Numpy functions:

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Identity matrix: 
    Diagonal elements are 1:

In [13]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
print(f'Array: {arr}')
print(f'Shape: {np.shape(arr)}')
print(f'No of dimension: {np.ndim(arr)}')
print(f'No of elements: {np.size(arr)}')
print(f'Data type: {arr.dtype}')

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
No of dimension: 2
No of elements: 6
Data type: int32
